# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

env:
  - CGO_ENABLED=0

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy -compat=1.17
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - goos:
      - linux
      - windows
      - darwin
    binary: ./vault/plugins/vault-plugin-secrets-omd-reader
    main: ./pkg/cmd/vault-plugin-secrets-omd-reader/main.go
release:
  draft: true
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^ci:'
      - '^docs:'
      - '^test:'
      - '^style:'
      - '^refactor:'

dockers:
  - image_templates: 
    - "ghcr.io/fybrik/{{.ProjectName}}:latest"
    - "ghcr.io/fybrik/{{.ProjectName}}:{{ .Version }}"
    dockerfile: Dockerfile.goreleaser
    goos: linux
    goarch: amd64
    build_flag_templates:
      - --platform=linux/amd64
    skip_push: false
